// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication.proto

package communication;

public final class Communication {
  private Communication() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ElementInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ElementInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 total = 1;</code>
     */
    boolean hasTotal();
    /**
     * <code>required int32 total = 1;</code>
     */
    int getTotal();

    /**
     * <code>required int32 visible = 2;</code>
     */
    boolean hasVisible();
    /**
     * <code>required int32 visible = 2;</code>
     */
    int getVisible();
  }
  /**
   * Protobuf type {@code ElementInfo}
   */
  public  static final class ElementInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ElementInfo)
      ElementInfoOrBuilder {
    // Use ElementInfo.newBuilder() to construct.
    private ElementInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ElementInfo() {
      total_ = 0;
      visible_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ElementInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              total_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              visible_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return communication.Communication.internal_static_ElementInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return communication.Communication.internal_static_ElementInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              communication.Communication.ElementInfo.class, communication.Communication.ElementInfo.Builder.class);
    }

    private int bitField0_;
    public static final int TOTAL_FIELD_NUMBER = 1;
    private int total_;
    /**
     * <code>required int32 total = 1;</code>
     */
    public boolean hasTotal() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 total = 1;</code>
     */
    public int getTotal() {
      return total_;
    }

    public static final int VISIBLE_FIELD_NUMBER = 2;
    private int visible_;
    /**
     * <code>required int32 visible = 2;</code>
     */
    public boolean hasVisible() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 visible = 2;</code>
     */
    public int getVisible() {
      return visible_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTotal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVisible()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, total_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, visible_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, total_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, visible_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof communication.Communication.ElementInfo)) {
        return super.equals(obj);
      }
      communication.Communication.ElementInfo other = (communication.Communication.ElementInfo) obj;

      boolean result = true;
      result = result && (hasTotal() == other.hasTotal());
      if (hasTotal()) {
        result = result && (getTotal()
            == other.getTotal());
      }
      result = result && (hasVisible() == other.hasVisible());
      if (hasVisible()) {
        result = result && (getVisible()
            == other.getVisible());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasTotal()) {
        hash = (37 * hash) + TOTAL_FIELD_NUMBER;
        hash = (53 * hash) + getTotal();
      }
      if (hasVisible()) {
        hash = (37 * hash) + VISIBLE_FIELD_NUMBER;
        hash = (53 * hash) + getVisible();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static communication.Communication.ElementInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static communication.Communication.ElementInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static communication.Communication.ElementInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static communication.Communication.ElementInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static communication.Communication.ElementInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static communication.Communication.ElementInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static communication.Communication.ElementInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static communication.Communication.ElementInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static communication.Communication.ElementInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static communication.Communication.ElementInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(communication.Communication.ElementInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ElementInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ElementInfo)
        communication.Communication.ElementInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return communication.Communication.internal_static_ElementInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return communication.Communication.internal_static_ElementInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                communication.Communication.ElementInfo.class, communication.Communication.ElementInfo.Builder.class);
      }

      // Construct using communication.Communication.ElementInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        total_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        visible_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return communication.Communication.internal_static_ElementInfo_descriptor;
      }

      public communication.Communication.ElementInfo getDefaultInstanceForType() {
        return communication.Communication.ElementInfo.getDefaultInstance();
      }

      public communication.Communication.ElementInfo build() {
        communication.Communication.ElementInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public communication.Communication.ElementInfo buildPartial() {
        communication.Communication.ElementInfo result = new communication.Communication.ElementInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.total_ = total_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.visible_ = visible_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof communication.Communication.ElementInfo) {
          return mergeFrom((communication.Communication.ElementInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(communication.Communication.ElementInfo other) {
        if (other == communication.Communication.ElementInfo.getDefaultInstance()) return this;
        if (other.hasTotal()) {
          setTotal(other.getTotal());
        }
        if (other.hasVisible()) {
          setVisible(other.getVisible());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTotal()) {
          return false;
        }
        if (!hasVisible()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        communication.Communication.ElementInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (communication.Communication.ElementInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int total_ ;
      /**
       * <code>required int32 total = 1;</code>
       */
      public boolean hasTotal() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 total = 1;</code>
       */
      public int getTotal() {
        return total_;
      }
      /**
       * <code>required int32 total = 1;</code>
       */
      public Builder setTotal(int value) {
        bitField0_ |= 0x00000001;
        total_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 total = 1;</code>
       */
      public Builder clearTotal() {
        bitField0_ = (bitField0_ & ~0x00000001);
        total_ = 0;
        onChanged();
        return this;
      }

      private int visible_ ;
      /**
       * <code>required int32 visible = 2;</code>
       */
      public boolean hasVisible() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 visible = 2;</code>
       */
      public int getVisible() {
        return visible_;
      }
      /**
       * <code>required int32 visible = 2;</code>
       */
      public Builder setVisible(int value) {
        bitField0_ |= 0x00000002;
        visible_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 visible = 2;</code>
       */
      public Builder clearVisible() {
        bitField0_ = (bitField0_ & ~0x00000002);
        visible_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ElementInfo)
    }

    // @@protoc_insertion_point(class_scope:ElementInfo)
    private static final communication.Communication.ElementInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new communication.Communication.ElementInfo();
    }

    public static communication.Communication.ElementInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ElementInfo>
        PARSER = new com.google.protobuf.AbstractParser<ElementInfo>() {
      public ElementInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ElementInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ElementInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ElementInfo> getParserForType() {
      return PARSER;
    }

    public communication.Communication.ElementInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ElementsCountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ElementsCount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .ElementInfo&gt; elementInfos = 1;</code>
     */
    int getElementInfosCount();
    /**
     * <code>map&lt;string, .ElementInfo&gt; elementInfos = 1;</code>
     */
    boolean containsElementInfos(
        java.lang.String key);
    /**
     * Use {@link #getElementInfosMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, communication.Communication.ElementInfo>
    getElementInfos();
    /**
     * <code>map&lt;string, .ElementInfo&gt; elementInfos = 1;</code>
     */
    java.util.Map<java.lang.String, communication.Communication.ElementInfo>
    getElementInfosMap();
    /**
     * <code>map&lt;string, .ElementInfo&gt; elementInfos = 1;</code>
     */

    communication.Communication.ElementInfo getElementInfosOrDefault(
        java.lang.String key,
        communication.Communication.ElementInfo defaultValue);
    /**
     * <code>map&lt;string, .ElementInfo&gt; elementInfos = 1;</code>
     */

    communication.Communication.ElementInfo getElementInfosOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code ElementsCount}
   */
  public  static final class ElementsCount extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ElementsCount)
      ElementsCountOrBuilder {
    // Use ElementsCount.newBuilder() to construct.
    private ElementsCount(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ElementsCount() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ElementsCount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                elementInfos_ = com.google.protobuf.MapField.newMapField(
                    ElementInfosDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, communication.Communication.ElementInfo>
              elementInfos = input.readMessage(
                  ElementInfosDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              elementInfos_.getMutableMap().put(elementInfos.getKey(), elementInfos.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return communication.Communication.internal_static_ElementsCount_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetElementInfos();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return communication.Communication.internal_static_ElementsCount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              communication.Communication.ElementsCount.class, communication.Communication.ElementsCount.Builder.class);
    }

    public static final int ELEMENTINFOS_FIELD_NUMBER = 1;
    private static final class ElementInfosDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, communication.Communication.ElementInfo> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, communication.Communication.ElementInfo>newDefaultInstance(
                  communication.Communication.internal_static_ElementsCount_ElementInfosEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  communication.Communication.ElementInfo.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, communication.Communication.ElementInfo> elementInfos_;
    private com.google.protobuf.MapField<java.lang.String, communication.Communication.ElementInfo>
    internalGetElementInfos() {
      if (elementInfos_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ElementInfosDefaultEntryHolder.defaultEntry);
      }
      return elementInfos_;
    }

    public int getElementInfosCount() {
      return internalGetElementInfos().getMap().size();
    }
    /**
     * <code>map&lt;string, .ElementInfo&gt; elementInfos = 1;</code>
     */

    public boolean containsElementInfos(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetElementInfos().getMap().containsKey(key);
    }
    /**
     * Use {@link #getElementInfosMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, communication.Communication.ElementInfo> getElementInfos() {
      return getElementInfosMap();
    }
    /**
     * <code>map&lt;string, .ElementInfo&gt; elementInfos = 1;</code>
     */

    public java.util.Map<java.lang.String, communication.Communication.ElementInfo> getElementInfosMap() {
      return internalGetElementInfos().getMap();
    }
    /**
     * <code>map&lt;string, .ElementInfo&gt; elementInfos = 1;</code>
     */

    public communication.Communication.ElementInfo getElementInfosOrDefault(
        java.lang.String key,
        communication.Communication.ElementInfo defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, communication.Communication.ElementInfo> map =
          internalGetElementInfos().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .ElementInfo&gt; elementInfos = 1;</code>
     */

    public communication.Communication.ElementInfo getElementInfosOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, communication.Communication.ElementInfo> map =
          internalGetElementInfos().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (communication.Communication.ElementInfo item : getElementInfos().values()) {
        if (!item.isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (java.util.Map.Entry<java.lang.String, communication.Communication.ElementInfo> entry
           : internalGetElementInfos().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, communication.Communication.ElementInfo>
        elementInfos = ElementInfosDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(1, elementInfos);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, communication.Communication.ElementInfo> entry
           : internalGetElementInfos().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, communication.Communication.ElementInfo>
        elementInfos = ElementInfosDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, elementInfos);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof communication.Communication.ElementsCount)) {
        return super.equals(obj);
      }
      communication.Communication.ElementsCount other = (communication.Communication.ElementsCount) obj;

      boolean result = true;
      result = result && internalGetElementInfos().equals(
          other.internalGetElementInfos());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (!internalGetElementInfos().getMap().isEmpty()) {
        hash = (37 * hash) + ELEMENTINFOS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetElementInfos().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static communication.Communication.ElementsCount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static communication.Communication.ElementsCount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static communication.Communication.ElementsCount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static communication.Communication.ElementsCount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static communication.Communication.ElementsCount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static communication.Communication.ElementsCount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static communication.Communication.ElementsCount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static communication.Communication.ElementsCount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static communication.Communication.ElementsCount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static communication.Communication.ElementsCount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(communication.Communication.ElementsCount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ElementsCount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ElementsCount)
        communication.Communication.ElementsCountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return communication.Communication.internal_static_ElementsCount_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetElementInfos();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableElementInfos();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return communication.Communication.internal_static_ElementsCount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                communication.Communication.ElementsCount.class, communication.Communication.ElementsCount.Builder.class);
      }

      // Construct using communication.Communication.ElementsCount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableElementInfos().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return communication.Communication.internal_static_ElementsCount_descriptor;
      }

      public communication.Communication.ElementsCount getDefaultInstanceForType() {
        return communication.Communication.ElementsCount.getDefaultInstance();
      }

      public communication.Communication.ElementsCount build() {
        communication.Communication.ElementsCount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public communication.Communication.ElementsCount buildPartial() {
        communication.Communication.ElementsCount result = new communication.Communication.ElementsCount(this);
        int from_bitField0_ = bitField0_;
        result.elementInfos_ = internalGetElementInfos();
        result.elementInfos_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof communication.Communication.ElementsCount) {
          return mergeFrom((communication.Communication.ElementsCount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(communication.Communication.ElementsCount other) {
        if (other == communication.Communication.ElementsCount.getDefaultInstance()) return this;
        internalGetMutableElementInfos().mergeFrom(
            other.internalGetElementInfos());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (communication.Communication.ElementInfo item : getElementInfos().values()) {
          if (!item.isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        communication.Communication.ElementsCount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (communication.Communication.ElementsCount) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, communication.Communication.ElementInfo> elementInfos_;
      private com.google.protobuf.MapField<java.lang.String, communication.Communication.ElementInfo>
      internalGetElementInfos() {
        if (elementInfos_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ElementInfosDefaultEntryHolder.defaultEntry);
        }
        return elementInfos_;
      }
      private com.google.protobuf.MapField<java.lang.String, communication.Communication.ElementInfo>
      internalGetMutableElementInfos() {
        onChanged();;
        if (elementInfos_ == null) {
          elementInfos_ = com.google.protobuf.MapField.newMapField(
              ElementInfosDefaultEntryHolder.defaultEntry);
        }
        if (!elementInfos_.isMutable()) {
          elementInfos_ = elementInfos_.copy();
        }
        return elementInfos_;
      }

      public int getElementInfosCount() {
        return internalGetElementInfos().getMap().size();
      }
      /**
       * <code>map&lt;string, .ElementInfo&gt; elementInfos = 1;</code>
       */

      public boolean containsElementInfos(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetElementInfos().getMap().containsKey(key);
      }
      /**
       * Use {@link #getElementInfosMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, communication.Communication.ElementInfo> getElementInfos() {
        return getElementInfosMap();
      }
      /**
       * <code>map&lt;string, .ElementInfo&gt; elementInfos = 1;</code>
       */

      public java.util.Map<java.lang.String, communication.Communication.ElementInfo> getElementInfosMap() {
        return internalGetElementInfos().getMap();
      }
      /**
       * <code>map&lt;string, .ElementInfo&gt; elementInfos = 1;</code>
       */

      public communication.Communication.ElementInfo getElementInfosOrDefault(
          java.lang.String key,
          communication.Communication.ElementInfo defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, communication.Communication.ElementInfo> map =
            internalGetElementInfos().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .ElementInfo&gt; elementInfos = 1;</code>
       */

      public communication.Communication.ElementInfo getElementInfosOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, communication.Communication.ElementInfo> map =
            internalGetElementInfos().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearElementInfos() {
        getMutableElementInfos().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .ElementInfo&gt; elementInfos = 1;</code>
       */

      public Builder removeElementInfos(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableElementInfos().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, communication.Communication.ElementInfo>
      getMutableElementInfos() {
        return internalGetMutableElementInfos().getMutableMap();
      }
      /**
       * <code>map&lt;string, .ElementInfo&gt; elementInfos = 1;</code>
       */
      public Builder putElementInfos(
          java.lang.String key,
          communication.Communication.ElementInfo value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableElementInfos().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .ElementInfo&gt; elementInfos = 1;</code>
       */

      public Builder putAllElementInfos(
          java.util.Map<java.lang.String, communication.Communication.ElementInfo> values) {
        getMutableElementInfos().putAll(values);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ElementsCount)
    }

    // @@protoc_insertion_point(class_scope:ElementsCount)
    private static final communication.Communication.ElementsCount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new communication.Communication.ElementsCount();
    }

    public static communication.Communication.ElementsCount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ElementsCount>
        PARSER = new com.google.protobuf.AbstractParser<ElementsCount>() {
      public ElementsCount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ElementsCount(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ElementsCount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ElementsCount> getParserForType() {
      return PARSER;
    }

    public communication.Communication.ElementsCount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BoundingBoxOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BoundingBox)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double fromX = 1;</code>
     */
    boolean hasFromX();
    /**
     * <code>required double fromX = 1;</code>
     */
    double getFromX();

    /**
     * <code>required double toX = 2;</code>
     */
    boolean hasToX();
    /**
     * <code>required double toX = 2;</code>
     */
    double getToX();

    /**
     * <code>required double fromY = 3;</code>
     */
    boolean hasFromY();
    /**
     * <code>required double fromY = 3;</code>
     */
    double getFromY();

    /**
     * <code>required double toY = 4;</code>
     */
    boolean hasToY();
    /**
     * <code>required double toY = 4;</code>
     */
    double getToY();

    /**
     * <code>required double fromZ = 5;</code>
     */
    boolean hasFromZ();
    /**
     * <code>required double fromZ = 5;</code>
     */
    double getFromZ();

    /**
     * <code>required double toZ = 6;</code>
     */
    boolean hasToZ();
    /**
     * <code>required double toZ = 6;</code>
     */
    double getToZ();
  }
  /**
   * Protobuf type {@code BoundingBox}
   */
  public  static final class BoundingBox extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BoundingBox)
      BoundingBoxOrBuilder {
    // Use BoundingBox.newBuilder() to construct.
    private BoundingBox(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BoundingBox() {
      fromX_ = 0D;
      toX_ = 0D;
      fromY_ = 0D;
      toY_ = 0D;
      fromZ_ = 0D;
      toZ_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BoundingBox(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              fromX_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              toX_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              fromY_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              toY_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              fromZ_ = input.readDouble();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              toZ_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return communication.Communication.internal_static_BoundingBox_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return communication.Communication.internal_static_BoundingBox_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              communication.Communication.BoundingBox.class, communication.Communication.BoundingBox.Builder.class);
    }

    private int bitField0_;
    public static final int FROMX_FIELD_NUMBER = 1;
    private double fromX_;
    /**
     * <code>required double fromX = 1;</code>
     */
    public boolean hasFromX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double fromX = 1;</code>
     */
    public double getFromX() {
      return fromX_;
    }

    public static final int TOX_FIELD_NUMBER = 2;
    private double toX_;
    /**
     * <code>required double toX = 2;</code>
     */
    public boolean hasToX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double toX = 2;</code>
     */
    public double getToX() {
      return toX_;
    }

    public static final int FROMY_FIELD_NUMBER = 3;
    private double fromY_;
    /**
     * <code>required double fromY = 3;</code>
     */
    public boolean hasFromY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double fromY = 3;</code>
     */
    public double getFromY() {
      return fromY_;
    }

    public static final int TOY_FIELD_NUMBER = 4;
    private double toY_;
    /**
     * <code>required double toY = 4;</code>
     */
    public boolean hasToY() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double toY = 4;</code>
     */
    public double getToY() {
      return toY_;
    }

    public static final int FROMZ_FIELD_NUMBER = 5;
    private double fromZ_;
    /**
     * <code>required double fromZ = 5;</code>
     */
    public boolean hasFromZ() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required double fromZ = 5;</code>
     */
    public double getFromZ() {
      return fromZ_;
    }

    public static final int TOZ_FIELD_NUMBER = 6;
    private double toZ_;
    /**
     * <code>required double toZ = 6;</code>
     */
    public boolean hasToZ() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required double toZ = 6;</code>
     */
    public double getToZ() {
      return toZ_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFromX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFromY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFromZ()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToZ()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, fromX_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, toX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, fromY_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, toY_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, fromZ_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, toZ_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, fromX_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, toX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, fromY_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, toY_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, fromZ_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, toZ_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof communication.Communication.BoundingBox)) {
        return super.equals(obj);
      }
      communication.Communication.BoundingBox other = (communication.Communication.BoundingBox) obj;

      boolean result = true;
      result = result && (hasFromX() == other.hasFromX());
      if (hasFromX()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getFromX())
            == java.lang.Double.doubleToLongBits(
                other.getFromX()));
      }
      result = result && (hasToX() == other.hasToX());
      if (hasToX()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getToX())
            == java.lang.Double.doubleToLongBits(
                other.getToX()));
      }
      result = result && (hasFromY() == other.hasFromY());
      if (hasFromY()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getFromY())
            == java.lang.Double.doubleToLongBits(
                other.getFromY()));
      }
      result = result && (hasToY() == other.hasToY());
      if (hasToY()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getToY())
            == java.lang.Double.doubleToLongBits(
                other.getToY()));
      }
      result = result && (hasFromZ() == other.hasFromZ());
      if (hasFromZ()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getFromZ())
            == java.lang.Double.doubleToLongBits(
                other.getFromZ()));
      }
      result = result && (hasToZ() == other.hasToZ());
      if (hasToZ()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getToZ())
            == java.lang.Double.doubleToLongBits(
                other.getToZ()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasFromX()) {
        hash = (37 * hash) + FROMX_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getFromX()));
      }
      if (hasToX()) {
        hash = (37 * hash) + TOX_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getToX()));
      }
      if (hasFromY()) {
        hash = (37 * hash) + FROMY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getFromY()));
      }
      if (hasToY()) {
        hash = (37 * hash) + TOY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getToY()));
      }
      if (hasFromZ()) {
        hash = (37 * hash) + FROMZ_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getFromZ()));
      }
      if (hasToZ()) {
        hash = (37 * hash) + TOZ_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getToZ()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static communication.Communication.BoundingBox parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static communication.Communication.BoundingBox parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static communication.Communication.BoundingBox parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static communication.Communication.BoundingBox parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static communication.Communication.BoundingBox parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static communication.Communication.BoundingBox parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static communication.Communication.BoundingBox parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static communication.Communication.BoundingBox parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static communication.Communication.BoundingBox parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static communication.Communication.BoundingBox parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(communication.Communication.BoundingBox prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BoundingBox}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BoundingBox)
        communication.Communication.BoundingBoxOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return communication.Communication.internal_static_BoundingBox_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return communication.Communication.internal_static_BoundingBox_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                communication.Communication.BoundingBox.class, communication.Communication.BoundingBox.Builder.class);
      }

      // Construct using communication.Communication.BoundingBox.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        fromX_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        toX_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        fromY_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        toY_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        fromZ_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        toZ_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return communication.Communication.internal_static_BoundingBox_descriptor;
      }

      public communication.Communication.BoundingBox getDefaultInstanceForType() {
        return communication.Communication.BoundingBox.getDefaultInstance();
      }

      public communication.Communication.BoundingBox build() {
        communication.Communication.BoundingBox result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public communication.Communication.BoundingBox buildPartial() {
        communication.Communication.BoundingBox result = new communication.Communication.BoundingBox(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fromX_ = fromX_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.toX_ = toX_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fromY_ = fromY_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.toY_ = toY_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.fromZ_ = fromZ_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.toZ_ = toZ_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof communication.Communication.BoundingBox) {
          return mergeFrom((communication.Communication.BoundingBox)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(communication.Communication.BoundingBox other) {
        if (other == communication.Communication.BoundingBox.getDefaultInstance()) return this;
        if (other.hasFromX()) {
          setFromX(other.getFromX());
        }
        if (other.hasToX()) {
          setToX(other.getToX());
        }
        if (other.hasFromY()) {
          setFromY(other.getFromY());
        }
        if (other.hasToY()) {
          setToY(other.getToY());
        }
        if (other.hasFromZ()) {
          setFromZ(other.getFromZ());
        }
        if (other.hasToZ()) {
          setToZ(other.getToZ());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFromX()) {
          return false;
        }
        if (!hasToX()) {
          return false;
        }
        if (!hasFromY()) {
          return false;
        }
        if (!hasToY()) {
          return false;
        }
        if (!hasFromZ()) {
          return false;
        }
        if (!hasToZ()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        communication.Communication.BoundingBox parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (communication.Communication.BoundingBox) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double fromX_ ;
      /**
       * <code>required double fromX = 1;</code>
       */
      public boolean hasFromX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double fromX = 1;</code>
       */
      public double getFromX() {
        return fromX_;
      }
      /**
       * <code>required double fromX = 1;</code>
       */
      public Builder setFromX(double value) {
        bitField0_ |= 0x00000001;
        fromX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double fromX = 1;</code>
       */
      public Builder clearFromX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fromX_ = 0D;
        onChanged();
        return this;
      }

      private double toX_ ;
      /**
       * <code>required double toX = 2;</code>
       */
      public boolean hasToX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double toX = 2;</code>
       */
      public double getToX() {
        return toX_;
      }
      /**
       * <code>required double toX = 2;</code>
       */
      public Builder setToX(double value) {
        bitField0_ |= 0x00000002;
        toX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double toX = 2;</code>
       */
      public Builder clearToX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        toX_ = 0D;
        onChanged();
        return this;
      }

      private double fromY_ ;
      /**
       * <code>required double fromY = 3;</code>
       */
      public boolean hasFromY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double fromY = 3;</code>
       */
      public double getFromY() {
        return fromY_;
      }
      /**
       * <code>required double fromY = 3;</code>
       */
      public Builder setFromY(double value) {
        bitField0_ |= 0x00000004;
        fromY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double fromY = 3;</code>
       */
      public Builder clearFromY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fromY_ = 0D;
        onChanged();
        return this;
      }

      private double toY_ ;
      /**
       * <code>required double toY = 4;</code>
       */
      public boolean hasToY() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double toY = 4;</code>
       */
      public double getToY() {
        return toY_;
      }
      /**
       * <code>required double toY = 4;</code>
       */
      public Builder setToY(double value) {
        bitField0_ |= 0x00000008;
        toY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double toY = 4;</code>
       */
      public Builder clearToY() {
        bitField0_ = (bitField0_ & ~0x00000008);
        toY_ = 0D;
        onChanged();
        return this;
      }

      private double fromZ_ ;
      /**
       * <code>required double fromZ = 5;</code>
       */
      public boolean hasFromZ() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required double fromZ = 5;</code>
       */
      public double getFromZ() {
        return fromZ_;
      }
      /**
       * <code>required double fromZ = 5;</code>
       */
      public Builder setFromZ(double value) {
        bitField0_ |= 0x00000010;
        fromZ_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double fromZ = 5;</code>
       */
      public Builder clearFromZ() {
        bitField0_ = (bitField0_ & ~0x00000010);
        fromZ_ = 0D;
        onChanged();
        return this;
      }

      private double toZ_ ;
      /**
       * <code>required double toZ = 6;</code>
       */
      public boolean hasToZ() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required double toZ = 6;</code>
       */
      public double getToZ() {
        return toZ_;
      }
      /**
       * <code>required double toZ = 6;</code>
       */
      public Builder setToZ(double value) {
        bitField0_ |= 0x00000020;
        toZ_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double toZ = 6;</code>
       */
      public Builder clearToZ() {
        bitField0_ = (bitField0_ & ~0x00000020);
        toZ_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BoundingBox)
    }

    // @@protoc_insertion_point(class_scope:BoundingBox)
    private static final communication.Communication.BoundingBox DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new communication.Communication.BoundingBox();
    }

    public static communication.Communication.BoundingBox getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BoundingBox>
        PARSER = new com.google.protobuf.AbstractParser<BoundingBox>() {
      public BoundingBox parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BoundingBox(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BoundingBox> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BoundingBox> getParserForType() {
      return PARSER;
    }

    public communication.Communication.BoundingBox getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ElementInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ElementInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ElementsCount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ElementsCount_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ElementsCount_ElementInfosEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ElementsCount_ElementInfosEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BoundingBox_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BoundingBox_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023communication.proto\"-\n\013ElementInfo\022\r\n\005" +
      "total\030\001 \002(\005\022\017\n\007visible\030\002 \002(\005\"\212\001\n\rElement" +
      "sCount\0226\n\014elementInfos\030\001 \003(\0132 .ElementsC" +
      "ount.ElementInfosEntry\032A\n\021ElementInfosEn" +
      "try\022\013\n\003key\030\001 \001(\t\022\033\n\005value\030\002 \001(\0132\014.Elemen" +
      "tInfo:\0028\001\"a\n\013BoundingBox\022\r\n\005fromX\030\001 \002(\001\022" +
      "\013\n\003toX\030\002 \002(\001\022\r\n\005fromY\030\003 \002(\001\022\013\n\003toY\030\004 \002(\001" +
      "\022\r\n\005fromZ\030\005 \002(\001\022\013\n\003toZ\030\006 \002(\001B\036\n\rcommunic" +
      "ationB\rCommunication"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ElementInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ElementInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ElementInfo_descriptor,
        new java.lang.String[] { "Total", "Visible", });
    internal_static_ElementsCount_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ElementsCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ElementsCount_descriptor,
        new java.lang.String[] { "ElementInfos", });
    internal_static_ElementsCount_ElementInfosEntry_descriptor =
      internal_static_ElementsCount_descriptor.getNestedTypes().get(0);
    internal_static_ElementsCount_ElementInfosEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ElementsCount_ElementInfosEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_BoundingBox_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BoundingBox_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BoundingBox_descriptor,
        new java.lang.String[] { "FromX", "ToX", "FromY", "ToY", "FromZ", "ToZ", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
